const $ = (sel) => document.querySelector(sel);
const app = $('#app');
const store = {
  get(key, fallback) { try { return JSON.parse(localStorage.getItem(key)) ?? fallback; } catch { return fallback; } },
  set(key, value) { localStorage.setItem(key, JSON.stringify(value)); }
};
function completed(){ return store.get('completedLessons', []); }
function bookmarks(){ return store.get('bookmarks', []); }
function quizScores(){ return store.get('quizScores', {}); }
function pct(){ return Math.round((completed().length / LESSONS.length) * 100); }
function lessonBySlug(slug){ return LESSONS.find(l => l.slug === slug); }
function moduleById(id){ return MODULES.find(m => m.id === id); }
function moduleLessons(id){ return LESSONS.filter(l => l.moduleId === id); }
function setActiveNav(){ document.querySelectorAll('.nav a').forEach(a => a.classList.toggle('active', a.getAttribute('href') === location.hash)); }
function render(){ setActiveNav(); const hash = location.hash || '#home'; const [route, param] = hash.replace('#','').split('/');
  if(route === 'dashboard') return dashboard();
  if(route === 'curriculum') return curriculum();
  if(route === 'module') return modulePage(param);
  if(route === 'lesson') return lessonPage(param);
  if(route === 'quiz') return quizPage(param);
  if(route === 'practice') return practice();
  if(route === 'resources') return resources();
  if(route === 'capstone') return capstone();
  if(route === 'search') return searchPage();
  return home();
}
function shell(content){ app.innerHTML = `<div class="container">${content}</div>`; }
function home(){ shell(`
<section class="hero">
  <div><span class="eyebrow">✨ Free • Beginner friendly • Static version</span><h1>Learn Power BI from scratch.</h1><p class="lead">A hands-on path from your first report to dashboards, DAX, data modeling, and a portfolio capstone. No login needed — progress saves in your browser.</p><div class="actions"><a class="btn" href="#dashboard">Start learning →</a><a class="btn secondary" href="#quiz/final-exam">Take skill test</a></div></div>
  <div class="card"><h3>Your learning path</h3><div class="stat"><span>Modules</span><strong>${MODULES.length}</strong></div><div class="stat"><span>Lessons</span><strong>${LESSONS.length}</strong></div><div class="stat"><span>Quizzes</span><strong>${QUIZZES.length}</strong></div><div class="stat"><span>Saved progress</span><strong>${pct()}%</strong></div><div class="progress-track"><div class="progress-fill" style="width:${pct()}%"></div></div></div>
</section>
<section class="section"><h2>What you’ll build</h2><div class="grid three">${['Clean messy datasets','Model fact and dimension tables','Create DAX measures','Build interactive dashboards','Use slicers and drill-through','Complete a capstone project'].map(x=>`<div class="card"><h3>${x}</h3><p>Practice this skill through lessons, quizzes, and browser-based tasks.</p></div>`).join('')}</div></section>
<section class="section"><h2>8-module curriculum</h2><div class="grid four">${MODULES.map(m=>`<a class="card module-card" href="#module/${m.id}"><h3>${m.icon} ${m.title}</h3><p>${m.description}</p></a>`).join('')}</div></section>`); }
function dashboard(){ const done=completed(); const xp=done.length*50; const last=LESSONS.find(l=>!done.includes(l.id)) || LESSONS[0]; shell(`<section class="section"><h2>Dashboard</h2><p class="lead">Track your browser-only learning progress.</p><div class="grid three"><div class="card"><h3>${pct()}% complete</h3><div class="progress-track"><div class="progress-fill" style="width:${pct()}%"></div></div><p>${done.length} of ${LESSONS.length} lessons complete</p></div><div class="card"><h3>${xp} XP</h3><p>Earn 50 XP for each completed lesson.</p></div><div class="card"><h3>${Object.keys(quizScores()).length} quiz attempts</h3><p>Scores are saved locally.</p></div></div><div class="card" style="margin-top:18px"><h3>Recommended next lesson</h3><p>${last.title}</p><a class="btn" href="#lesson/${last.slug}">Resume learning</a></div></section>`); }
function curriculum(){ shell(`<section class="section"><h2>Curriculum</h2><input id="q" class="searchbar" placeholder="Search lessons, DAX, modeling, cleaning..." oninput="filterCurriculum(this.value)"><div id="currList">${curriculumList(LESSONS)}</div></section>`); }
function curriculumList(items){ return MODULES.map(m=>{ const lessons=items.filter(l=>l.moduleId===m.id); if(!lessons.length) return ''; return `<div class="card" style="margin-bottom:18px"><h3>${m.icon} ${m.title}</h3><p>${m.description}</p>${lessons.map(l=>lessonRow(l)).join('')}</div>`; }).join(''); }
function lessonRow(l){ const done=completed().includes(l.id); const bm=bookmarks().includes(l.id); return `<div class="lesson-row"><div><strong>${done?'✅':'○'} ${l.title}</strong><br><small>${l.summary} • ${l.minutes} min ${bm?'• ★ bookmarked':''}</small></div><a class="btn small secondary" href="#lesson/${l.slug}">Open</a></div>`; }
window.filterCurriculum = (v) => { const term=v.toLowerCase(); $('#currList').innerHTML = curriculumList(LESSONS.filter(l => [l.title,l.summary,moduleById(l.moduleId).title].join(' ').toLowerCase().includes(term))); };
function modulePage(id){ const m=moduleById(id); if(!m) return curriculum(); shell(`<section class="section"><a href="#curriculum">← Curriculum</a><h2>${m.icon} ${m.title}</h2><p class="lead">${m.description}</p><div class="card">${moduleLessons(id).map(lessonRow).join('')}</div><div class="actions"><a class="btn secondary" href="#quiz/${id==='intro'?'power-bi-basics':id==='query'?'data-cleaning':id==='modeling'?'data-modeling':id==='dax'?'dax-fundamentals':'final-exam'}">Take related quiz</a></div></section>`); }
function lessonPage(slug){ const l=lessonBySlug(slug); if(!l) return curriculum(); const m=moduleById(l.moduleId); const done=completed().includes(l.id); const bm=bookmarks().includes(l.id); const siblings=moduleLessons(l.moduleId); const idx=siblings.findIndex(x=>x.id===l.id); const prev=siblings[idx-1], next=siblings[idx+1]; shell(`<section class="section"><a href="#module/${m.id}">← ${m.title}</a><div class="card lesson-content"><span class="badge ${done?'done':'warn'}">${done?'Completed':'In progress'}</span><h2>${l.title}</h2><p class="lead">${l.summary}</p><h3>Concept</h3><p>${lessonText(l)}</p><h3>Step-by-step practice</h3><ol>${l.steps.map(s=>`<li>${s}</li>`).join('')}</ol><h3>Mini task</h3><p>Open Power BI Desktop and complete the steps above. If you do not have it installed, write what each step would change in the data model or report.</p><div class="actions"><button class="btn" onclick="markDone('${l.id}')">${done?'Mark incomplete':'Mark complete'} </button><button class="btn secondary" onclick="toggleBm('${l.id}')">${bm?'Remove bookmark':'Bookmark'}</button></div></div><div class="actions">${prev?`<a class="btn secondary" href="#lesson/${prev.slug}">← Previous</a>`:''}${next?`<a class="btn" href="#lesson/${next.slug}">Next →</a>`:`<a class="btn" href="#curriculum">Back to curriculum</a>`}</div></section>`); }
function lessonText(l){ const map={intro:'Power BI helps turn raw business data into useful reports and dashboards. In this lesson, focus on the decision a user needs to make, not only the chart you want to create.',install:'Power BI Desktop is where most report development begins. Learning the interface makes every later step easier.',data:'Good analysis starts with reliable source data. Import carefully, check column types, and profile data before building visuals.',query:'Power Query records cleaning steps so messy data can be fixed consistently every refresh.',modeling:'A clean model is the foundation of reliable dashboards. Relationships and star schemas reduce confusion and make DAX easier.',visuals:'Visuals should answer questions quickly. Use interaction only when it helps users explore data.',dax:'DAX measures calculate results based on the current filter context. This is what makes Power BI dynamic.',publish:'A finished dashboard needs polish, testing, and a clear explanation of the decisions it supports.'}; return map[l.moduleId] || map.intro; }
window.markDone = (id) => { let d=completed(); d=d.includes(id)?d.filter(x=>x!==id):[...d,id]; store.set('completedLessons',d); render(); };
window.toggleBm = (id) => { let b=bookmarks(); b=b.includes(id)?b.filter(x=>x!==id):[...b,id]; store.set('bookmarks',b); render(); };
function quizPage(slug){ const q=QUIZZES.find(x=>x.slug===slug) || QUIZZES[0]; shell(`<section class="section"><h2>${q.title}</h2><p>Choose one answer for each question. You’ll get instant feedback.</p><div id="quiz">${q.questions.map((qq,i)=>`<div class="card" style="margin-bottom:14px"><h3>${i+1}. ${qq[0]}</h3>${qq[1].map((opt,j)=>`<button class="quiz-option" onclick="answer('${q.slug}',${i},${j},${qq[2]}, this)">${opt}</button>`).join('')}<p id="ex-${i}"></p></div>`).join('')}<button class="btn" onclick="finishQuiz('${q.slug}',${q.questions.length})">Finish quiz</button></div><div id="quizResult"></div></section>`); }
window.answer = (slug,i,j,correct,btn) => { const box=btn.parentElement; box.querySelectorAll('.quiz-option').forEach(b=>b.disabled=true); btn.classList.add(j===correct?'correct':'wrong'); box.querySelectorAll('.quiz-option')[correct].classList.add('correct'); const q=QUIZZES.find(x=>x.slug===slug); $(`#ex-${i}`).innerHTML = `<strong>${j===correct?'Correct':'Not quite'}.</strong> ${q.questions[i][3]}`; const answers=store.get(`answers-${slug}`,{}); answers[i]=j===correct; store.set(`answers-${slug}`,answers); };
window.finishQuiz = (slug,total) => { const answers=store.get(`answers-${slug}`,{}); const score=Object.values(answers).filter(Boolean).length; const scores=quizScores(); scores[slug]={score,total,date:new Date().toLocaleDateString()}; store.set('quizScores',scores); $('#quizResult').innerHTML=`<div class="card" style="margin-top:18px"><h3>Score: ${score}/${total}</h3><p>${score/total>=.7?'Great work — you passed.':'Review the lesson material and try again.'}</p></div>`; };
function practice(){ shell(`<section class="section"><h2>Practice Lab</h2><p class="lead">Upload a CSV to preview it in the browser. Nothing is uploaded to a server.</p><div class="grid two"><div class="card"><h3>Upload CSV</h3><input type="file" accept=".csv" onchange="previewCsv(event)"><div id="csvPreview" style="margin-top:16px"></div></div><div class="card"><h3>Practice tasks</h3><ol><li>Create KPI cards for total sales and quantity.</li><li>Clean missing or inconsistent categories.</li><li>Create a revenue or margin measure.</li><li>Build a regional sales bar chart.</li><li>Add slicers for product and month.</li></ol></div></div><h3>Sample datasets</h3><div class="grid three">${DATASETS.map(d=>`<div class="card"><h3>${d.name}</h3><p>${d.rows.length-1} sample rows</p><button class="btn small" onclick="downloadDataset('${d.name}')">Download CSV</button></div>`).join('')}</div></section>`); }
window.previewCsv = (e) => { const file=e.target.files[0]; if(!file) return; const reader=new FileReader(); reader.onload=()=>{ const rows=reader.result.split(/\r?\n/).filter(Boolean).slice(0,8).map(r=>r.split(',')); $('#csvPreview').innerHTML = table(rows); }; reader.readAsText(file); };
window.downloadDataset = (name) => { const d=DATASETS.find(x=>x.name===name); const csv=d.rows.map(r=>r.join(',')).join('\n'); const a=document.createElement('a'); a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv'})); a.download=name; a.click(); };
function table(rows){ return `<div class="table-wrap"><table>${rows.map((r,i)=>`<tr>${r.map(c=>i?`<td>${c}</td>`:`<th>${c}</th>`).join('')}</tr>`).join('')}</table></div>`; }
function resources(){ shell(`<section class="section"><h2>Resource Library</h2><div class="grid two">${RESOURCES.map(r=>`<div class="card"><h3>${r[0]}</h3><p>${r[1]}</p></div>`).join('')}</div><div class="card" style="margin-top:18px"><h3>Bookmarked lessons</h3>${bookmarks().length ? bookmarks().map(id=>lessonRow(LESSONS.find(l=>l.id===id))).join('') : '<div class="empty">No bookmarks yet.</div>'}</div></section>`); }
function capstone(){ const items=['Import and clean at least one dataset','Create a star-schema style model','Add at least five useful measures','Build a one-page executive dashboard','Add slicers and at least one drill-through/detail view','Write a short insight summary']; const checked=store.get('capstone',{}); shell(`<section class="section"><h2>Capstone Project</h2><p class="lead">Build a sales performance dashboard suitable for your portfolio.</p><div class="grid two"><div class="card checklist"><h3>Checklist</h3>${items.map((it,i)=>`<label><input type="checkbox" ${checked[i]?'checked':''} onchange="saveCapstone(${i},this.checked)"> ${it}</label>`).join('')}</div><div class="card"><h3>Project brief</h3><p>You are the BI analyst for a retail business. Your task is to clean sales data, model it, create DAX metrics, and present an executive dashboard with clear recommendations.</p><textarea id="notes" placeholder="Write your insights...">${store.get('capstoneNotes','')}</textarea><button class="btn" onclick="store.set('capstoneNotes',$('#notes').value); alert('Saved in this browser!')">Save notes</button></div></div></section>`); }
window.saveCapstone = (i,val) => { const c=store.get('capstone',{}); c[i]=val; store.set('capstone',c); };
function searchPage(){ curriculum(); }
$('#menuBtn').onclick = () => $('#nav').classList.toggle('open');
window.addEventListener('hashchange', render);
render();
